version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_DB_URL=mongodb://127.0.0.1:27017/convite
      - JWT_SECRET_KEY=n2WU4@&UTspg3Dddi^Gy%#U9%AfNBipXFK%gp$AKSrbYpuF&UM#MxF4SkJ5KefYA
      - SALT_WORK_FACTOR=4
    # volumes:
    #   - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
